### ISSUE TITLE
on iPad, left-image quality is poor

### ISSUE THREAD

**Issue by saldous** [dkcas11/CRNotifications#7] opened 2017-09-25 21:55 UTC
When using on an iPad, the left image quality is poor and a little pixelated since it's a larger size.

**Comment by dkcas11** [comment] 2017-10-02 08:08
The framework is not specifically supported on iPads, but i will have a look at the images and see if i can optimise them for the best quality possible.

**Comment by dkcas11** [comment] 2017-10-04 10:50
This has now been fixed in version 1.1.1. Can you test this on your device?

**Comment by saldous** [comment] 2017-10-04 14:21
This is what I see on iPad Pro (12.9inch):
![image](https://user-images.githubusercontent.com/3334306/31180853-b7a1efaa-a8ed-11e7-9509-9adbe08ca6a2.png)

**Comment by dkcas11** [comment] 2017-10-04 16:35
Weird, using the simulator (both 1st and 2nd gen) i get it correctly. Is this on an actual device or the simulator?
Also, how do you install the framework, manually or by Cocoapods?

![simulator screen shot - ipad pro 12 9-inch - 2017-10-04 at 18 30 36](https://user-images.githubusercontent.com/5683004/31187645-c7c43c2c-a932-11e7-8170-59db73b6740f.png)

**Comment by dkcas11** [comment] 2017-10-04 17:46
I have a fix in place that should solve the problem. I have tested all simulator devices where behaviour works as intended.

**Comment by saldous** [comment] 2017-10-04 17:51
I used iPad Pro (12.9inch) in simulator with iOS 11.

**Comment by dkcas11** [comment] 2017-10-04 19:10
I have updated the framework now and put in a development branch. Could you try and checkout the development branch like this?:
```pod 'CRNotifications', :git => 'https://github.com/dkcas11/CRNotifications.git', :branch => 'development'```

**Comment by dkcas11** [comment] 2017-10-05 18:28
Please let me know about your results.

**Comment by saldous** [comment] 2017-10-05 18:47
I didn't see any different. It pulled v1.1.2 with that in the Podfile. I see the Pod includes a DeviceManager.swift file, but I don't see it being used?
![image](https://user-images.githubusercontent.com/3334306/31246654-0ef37dc0-a9dc-11e7-9aab-4734147c017b.png)

**Comment by dkcas11** [comment] 2017-10-06 10:23
For some reason the changes were left out when i did the change. I have now tested that it works with a new project.

**Comment by saldous** [comment] 2017-10-06 14:10
Great, I just tried again and it now works, thank you so much! 👍 

iPad:
![image](https://user-images.githubusercontent.com/3334306/31281828-94ed7fa0-aa7e-11e7-84a9-92ead840de34.png)

iPhone X:
![image](https://user-images.githubusercontent.com/3334306/31281935-fec77c5a-aa7e-11e7-8f68-062fb2ad192f.png)


Also, let me know if you want me to open another issue for these minor items to support Swift 4:

In CRNotification.swift:

1. Line 20: Change UIFontWeightBold to: **UIFont.Weight.bold**
2. Line 26: Change UIFontWeightSemibold to: **UIFont.Weight.semibold**
3. Line 142: Change func dismissNotification() to: **@objc** func dismissNotification()

**Comment by dkcas11** [comment] 2017-10-06 14:37
No worries, glad you like it and thanks for reporting the issue :) 

I am already aware of the conversion for Swift 4, but i just wanted to finish this up before migrating to Swift 4 and archiving the master onto a Swift 3 branch.

**Closed as completed by dkcas11** 2017-10-06 14:37 UTC

**Comment by dkcas11** [comment] 2017-10-06 15:20
Current version has been updated for Swift 4. So just change your podfile back to `pod 'CRNotifications'`. 👍
